import { readFileSync } from "node:fs";
const url = process.argv[2];
const h = await (await fetch(url + "?nocache=" + Math.floor(Math.random()*1e6), { headers: { "User-Agent": "Mozilla/5.0" } })).text();
const marcado = h.replace(/<(style|script)\b[^>]*>[\s\S]*?<\/\1>/gi, "");
const frase = process.argv[3];
console.log("\n  " + url);
console.log("  bytes: " + h.length);
console.log("  frase del texto nuevo presente : " + (marcado.includes(frase) ? "SÍ" : "NO"));
const h2 = [...marcado.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/gi)].map(m => m[1].replace(/<[^>]+>/g,"").trim());
const h3 = [...marcado.matchAll(/<h3[^>]*>([\s\S]*?)<\/h3>/gi)].map(m => m[1].replace(/<[^>]+>/g,"").trim());
const h4 = [...marcado.matchAll(/<h4[^>]*>([\s\S]*?)<\/h4>/gi)].map(m => m[1].replace(/<[^>]+>/g,"").trim());
console.log("\n  H2 en la página (" + h2.length + "):");
h2.slice(0,8).forEach(x => console.log("     " + x.slice(0,80)));
console.log("  H3 (" + h3.length + "):");
h3.slice(0,10).forEach(x => console.log("     " + x.slice(0,80)));
console.log("  H4 (" + h4.length + "):");
h4.slice(0,6).forEach(x => console.log("     " + x.slice(0,80)));
const h1 = [...marcado.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m => m[1].replace(/<[^>]+>/g,"").trim());
console.log("\n  H1 (" + h1.length + "): " + h1.join(" | ").slice(0,80));
